### ISSUE TITLE
[Bug]: 웨일 브라우저에서 위치 정보를 정확하게 찾지 못하는 문제

### ISSUE THREAD

**Issue by cgk95** [Kernel360/E2E1-Anabada#198]
### 어떤 버그가 있었나요?

> 웨일 브라우저에서 위치 정보를 정확하게 찾지 못하는 문제가 있습니다.( 정확한 위치 :: 서울특별시 강남구 삼성동)

![image](https://github.com/Kernel360/E2E1-Anabada/assets/73059667/8ba8fa22-e039-4634-859f-445e1cd8c1c0)
<br>
![image](https://github.com/Kernel360/E2E1-Anabada/assets/73059667/08d83fb0-1ebf-4606-9411-06d8c4d40fc2)

### Version

1.0.0 (Default)

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
저희 서비스는 위치정보를 가져오는데에 navigator.geolocation 함수를 사용하여 접속한 네트워크의 위도 경도 정보를 가져오고 반환된 위도 경도로 카카오 API 위치정보를 가져와 사용자의 위치정보를 출력하고 있습니다.
해당 이슈는 navigator.geolocation 에서 잘못된 위도 경도를 가져온 것으로 확인됩니다. 라이브러리에서 잘 못된 정보를 가져오는 문제는 조치하는데에 제한이 있기때문에 번거로우시겠지만 재접속을 부탁드립니다.
