### ISSUE TITLE
[Bug]: 위치정보가 안불러와짐

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/E2E1-Anabada#199]
### 연락 정보

asdf@test.com

### 어떤 버그가 있었나요?

최초 로그인 후 위치정보 로딩이 안됨

![image](https://github.com/Kernel360/E2E1-Anabada/assets/44130863/13851ccd-a815-4b14-98c7-7daa97621874)

Request Header
<img width="1146" alt="image" src="https://github.com/Kernel360/E2E1-Anabada/assets/44130863/9a007684-e18f-4eea-a39d-17e573ddd435">

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### 로그 내역

{"message":"위치정보를 찾을 수 없습니다.","status":404}

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
브라우저에서 위치 권한을 허용해주셔야 서비스를 이용하실 수 있습니다.
![image](https://github.com/Kernel360/E2E1-Anabada/assets/59242594/0d3c7c74-2b18-4248-91b0-34c2d632e67d)
