### ISSUE TITLE
[Bug]: 교환 등록할 때 제목이 이상하게 달려요

### ISSUE THREAD

**Issue by yejincode** [Kernel360/E2E1-Anabada#200]
### 어떤 버그가 있었나요?

거래 유형을 원해요, 나눠요로 한 후 , 물건을 입력하면 제목이 드려요 로 입력됩니다. 
![image](https://github.com/Kernel360/E2E1-Anabada/assets/69861207/b61e9588-c2a2-401f-b2ed-115beb4167bb)

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
버그인지는 모르겠지만, 원해요인데 나눌물건이 뜹니다. 원하는 물건으로 표현이 바뀌면 더 좋을 것 같습니다.
-> 원해요 거래유형은 글 작성자가 자신의 나눌 상품을 제시하고 바꾸고싶은 물건은 상대방이 제시하는 유형입니다. 따라서 나의 상품이 '드려요 ' 라고 표시되는게 올바른 현상임을 알려드립니다.
