### ISSUE TITLE
[Bug]: FAQ를 수정할 수 있어요

### ISSUE THREAD

**Issue by ShineCorine** [Kernel360/E2E1-Anabada#201]
### 어떤 버그가 있었나요?

로그인한 사용자가 다른 사람이 쓴 FAQ를 수정하거나 삭제할 수 있어요

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by fingersdanny** [comment]
의견 남겨주셔서 감사합니다. 해당 부분 확인 후 수정하겠습니다.
