### ISSUE TITLE
[Bug]: 내용 길이 초과 시 undefined

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/E2E1-Anabada#202]
### 연락 정보

asdf@test.com

### 어떤 버그가 있었나요?

내용 초과 시 undefined 에러 발생
![image](https://github.com/Kernel360/E2E1-Anabada/assets/44130863/10a69d1e-1a49-4479-ba40-3d1efba7076f)

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### 로그 내역

```shell
{
    "timestamp": "2023-11-22T02:48:54.601+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/v1/trades"
}
```

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
브라우저에서 위치 권한이 없어서 오류가 발생한것으로 확인됩니다.
위치권한이 없을 때 해당 메뉴에 접근하지 못하도록 조치하였습니다.
