### ISSUE TITLE
[Bug]: 로그인이 만료된 후에 새로고침 시 undefined 및 사용자 정보 미노출

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/E2E1-Anabada#203]
### 연락 정보

asdf@test.com

### 어떤 버그가 있었나요?

로그인이 만료되고 나서 새로고침하거나 다른 api를 호출하면 undefined 발생, 우측 상단 사용자 정보가 보이지 않음

![image](https://github.com/Kernel360/E2E1-Anabada/assets/44130863/9d886c64-c260-49dd-af41-1a259796e4d2)

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
해당 이슈 해결하여 재 배포 진행했습니다.
