### ISSUE TITLE
[Bug]: 원해요, 검색

### ISSUE THREAD

**Issue by aacara** [Kernel360/E2E1-Anabada#204]
### 어떤 버그가 있었나요?

1. 버그인지는 모르겠지만, 원해요인데 나눌물건이 뜹니다. 
-> 원하는 물건으로 표현이 바뀌면 더 좋을 것 같습니다.
![image](https://github.com/Kernel360/E2E1-Anabada/assets/86637372/36d85595-1173-41ba-afde-d78774f50d13)
2.  검색할 때 정확하지 않으면 검색이 안되고 있습니다. 
-> like를 써서 키워드를 포함하고 있으면 검색되도록 수정하면 좋을 것 같습니다.
![image](https://github.com/Kernel360/E2E1-Anabada/assets/86637372/5defd899-68c6-4412-b864-bc409962a540)
![image](https://github.com/Kernel360/E2E1-Anabada/assets/86637372/84fbc9ce-f434-476a-a25e-df8e4515ae42)

### Version

1.0.0 (Default)

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
1. 버그인지는 모르겠지만, 원해요인데 나눌물건이 뜹니다. 원하는 물건으로 표현이 바뀌면 더 좋을 것 같습니다.
-> 원해요 거래유형은 글 작성자가 자신의 나눌 상품을 제시하고 바꾸고싶은 물건은 상대방이 제시하는 유형입니다. 따라서 나의 상품이 '드려요 ' 라고 표시되는게 올바른 현상임을 알려드립니다.

2. 검색할 때 정확하지 않으면 검색이 안되고 있습니다. like를 써서 키워드를 포함하고 있으면 검색되도록 수정하면 좋을 것 같습니다.
-> 의견 반영하여 검색할 시 키워드를 포함한 모든 작성자의 글이 노출되도록 수정하였습니다.
