### ISSUE TITLE
[Bug]: 게시글 생성 에러

### ISSUE THREAD

**Issue by oxix97** [Kernel360/E2E1-Anabada#205]
### 어떤 버그가 있었나요?

교환 등록이 되지 않아요!
![image](https://github.com/Kernel360/E2E1-Anabada/assets/72330632/1672df49-7dc8-4bc5-8ec7-31724f77bd6f)
![스크린샷 2023-11-22 오후 12 04 00](https://github.com/Kernel360/E2E1-Anabada/assets/72330632/ffc2bece-8684-4aca-82c0-a912f10cb404)

### Version

1.0.0 (Default)

### 로그 내역

```shell
위의 사진 첨부합니다.
```

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by yoonseon12** [comment]
해당 이슈는 위치권한을  허용하지 않아 발생한 문제입니다.
브라우저에서 위치 권한을 허용 하시고 서비스를 이용해주시기 바랍니다.
