### ISSUE TITLE
[Bug]: 회원가입 할 때 생년월일 입력이 이상해요

### ISSUE THREAD

**Issue by mooncw** [Kernel360/E2E1-Anabada#207]
### 연락 정보

dusrktl4@gmail.com

### 어떤 버그가 있었나요?

연도에 6글자가 들어가요.
ex) 19941231를 입력했는데, 199412-03-01로 입력되요.

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by fingersdanny** [comment]
해당 부분 확인 후 수정 하였습니다. 의견 남겨주셔서 감사합니다~
