### ISSUE TITLE
[Bug]: redis 설치정보를 readme에 안내가 필요할것 같습니다.

### ISSUE THREAD

**Issue by HyunJunSon** [Kernel360/E2E1-Anabada#232]
### 어떤 버그가 있었나요?

redis 설치정보를 readme에 안내가 필요할것 같습니다.
redis설치 안해서 뜨는 에러가 발생합니다.

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] 아나바다의 Code of Conduct에 동의합니다.

**Comment by hodadako** [comment]
기술 스택에 레디스를 사용했다고 적혀 있어서 이 부분은 따로 안내가 불필요할거라 생각했습니다.
